import { IntermediateRepresentation, Entity, EntityField } from '../types/floe';

function mapSqlType(field: EntityField): string {
  if (typeof field.type === 'string' && field.type.startsWith('ref:')) {
    return 'UUID';
  }

  switch (field.type) {
    case 'string':
      return 'VARCHAR(255)';
    case 'text':
      return 'TEXT';
    case 'number':
      return field.name.includes('days') || field.name.includes('count') ? 'INTEGER' : 'NUMERIC(12, 2)';
    case 'boolean':
      return 'BOOLEAN';
    case 'date':
      return 'TIMESTAMPTZ';
    case 'enum':
      if (field.values && field.values.length > 0) {
        const allowed = field.values.map(v => `'${v}'`).join(', ');
        return `VARCHAR(50) CHECK (${field.name} IN (${allowed}))`;
      }
      return 'VARCHAR(50)';
    default:
      return 'TEXT';
  }
}

function mapPrismaType(field: EntityField): string {
  if (typeof field.type === 'string' && field.type.startsWith('ref:')) {
    return 'String';
  }
  switch (field.type) {
    case 'string':
      return 'String';
    case 'text':
      return 'String';
    case 'number':
      return field.name.includes('days') || field.name.includes('count') ? 'Int' : 'Float';
    case 'boolean':
      return 'Boolean';
    case 'date':
      return 'DateTime';
    case 'enum':
      return 'String';
    default:
      return 'String';
  }
}

export function compileDeterministicSqlDDL(ir: IntermediateRepresentation): string {
  const lines: string[] = [
    `-- =========================================================================`,
    `-- DETERMINISTIC POSTGRESQL DDL GENERATED BY FLOE COMPILER v1.0`,
    `-- Target Domain: ${ir.domain}`,
    `-- App Name: ${ir.name}`,
    `-- Compiled at: ${new Date().toISOString()}`,
    `-- =========================================================================\n`,
    `CREATE EXTENSION IF NOT EXISTS "uuid-ossp";\n`
  ];

  // 1. Compile Entities
  ir.entities.forEach((entity) => {
    const tableName = entity.name.toLowerCase() + 's';
    lines.push(`-- Table: ${entity.name} (${entity.description || 'Domain record'})`);
    lines.push(`CREATE TABLE IF NOT EXISTS ${tableName} (`);

    const fieldDefs: string[] = [];
    
    // Add primary key if not explicit in fields
    const hasId = entity.fields.some(f => f.name === 'id');
    if (!hasId) {
      fieldDefs.push(`    id UUID PRIMARY KEY DEFAULT uuid_generate_v4()`);
    }

    entity.fields.forEach(f => {
      const isPk = f.name === 'id';
      let def = `    ${f.name} ${isPk ? 'UUID PRIMARY KEY DEFAULT uuid_generate_v4()' : mapSqlType(f)}`;
      if (f.required && !isPk) {
        def += ' NOT NULL';
      }
      if (f.default !== undefined) {
        if (typeof f.default === 'string') {
          def += ` DEFAULT '${f.default}'`;
        } else {
          def += ` DEFAULT ${f.default}`;
        }
      }
      fieldDefs.push(def);
    });

    fieldDefs.push(`    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);
    fieldDefs.push(`    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()`);

    lines.push(fieldDefs.join(',\n'));
    lines.push(`);\n`);
  });

  // 2. Foreign Key constraints and Indexes
  lines.push(`-- Referential Integrity Constraints & Indexes`);
  ir.relationships.forEach(rel => {
    const sourceTable = rel.from.toLowerCase() + 's';
    const targetTable = rel.to.toLowerCase() + 's';
    lines.push(`ALTER TABLE ${sourceTable} ADD CONSTRAINT fk_${sourceTable}_${rel.field}`);
    lines.push(`    FOREIGN KEY (${rel.field}) REFERENCES ${targetTable}(id) ON DELETE RESTRICT;`);
    lines.push(`CREATE INDEX IF NOT EXISTS idx_${sourceTable}_${rel.field} ON ${sourceTable}(${rel.field});\n`);
  });

  // 3. Standard Floe Runtime Execution Tables (Mandatory in every generated app)
  lines.push(`-- =========================================================================`);
  lines.push(`-- STANDARD FLOE PLATFORM WORKFLOW RUNTIME SCHEMAS`);
  lines.push(`-- Enables deterministic execution tracking, audit trails & AI step metrics`);
  lines.push(`-- =========================================================================\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS workflow_runs (`);
  lines.push(`    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),`);
  lines.push(`    workflow_id VARCHAR(100) NOT NULL,`);
  lines.push(`    record_id UUID NOT NULL,`);
  lines.push(`    status VARCHAR(50) NOT NULL CHECK (status IN ('pending', 'running', 'completed', 'failed', 'paused_human')),`);
  lines.push(`    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),`);
  lines.push(`    completed_at TIMESTAMPTZ,`);
  lines.push(`    error TEXT`);
  lines.push(`);\n`);
  lines.push(`CREATE INDEX IF NOT EXISTS idx_workflow_runs_record ON workflow_runs(record_id);\n`);

  lines.push(`CREATE TABLE IF NOT EXISTS node_executions (`);
  lines.push(`    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),`);
  lines.push(`    workflow_run_id UUID NOT NULL REFERENCES workflow_runs(id) ON DELETE CASCADE,`);
  lines.push(`    node_id VARCHAR(100) NOT NULL,`);
  lines.push(`    execution_mode VARCHAR(50) NOT NULL CHECK (execution_mode IN ('deterministic', 'ai', 'agentic', 'human')),`);
  lines.push(`    status VARCHAR(50) NOT NULL CHECK (status IN ('queued', 'running', 'completed', 'failed', 'awaiting_human')),`);
  lines.push(`    input JSONB DEFAULT '{}'::jsonb,`);
  lines.push(`    output JSONB DEFAULT '{}'::jsonb,`);
  lines.push(`    started_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),`);
  lines.push(`    completed_at TIMESTAMPTZ,`);
  lines.push(`    error TEXT`);
  lines.push(`);\n`);
  lines.push(`CREATE INDEX IF NOT EXISTS idx_node_executions_run ON node_executions(workflow_run_id);\n`);

  return lines.join('\n');
}

export function compilePrismaSchema(ir: IntermediateRepresentation): string {
  const lines: string[] = [
    `// Prisma Schema generated deterministically by Floe Compiler`,
    `datasource db {`,
    `  provider = "postgresql"`,
    `  url      = env("DATABASE_URL")`,
    `}`,
    ``,
    `generator client {`,
    `  provider = "prisma-client-js"`,
    `}\n`
  ];

  ir.entities.forEach(entity => {
    lines.push(`model ${entity.name} {`);
    lines.push(`  id        String   @id @default(uuid())`);
    
    entity.fields.forEach(f => {
      if (f.name === 'id') return;
      const type = mapPrismaType(f);
      const optional = !f.required ? '?' : '';
      let line = `  ${f.name.padEnd(20)} ${type}${optional}`;
      if (f.default !== undefined) {
        line += ` @default(${typeof f.default === 'string' ? `"${f.default}"` : f.default})`;
      }
      lines.push(line);
    });

    lines.push(`  createdAt DateTime @default(now())`);
    lines.push(`  updatedAt DateTime @updatedAt`);
    lines.push(`}\n`);
  });

  lines.push(`model WorkflowRun {`);
  lines.push(`  id          String          @id @default(uuid())`);
  lines.push(`  workflowId  String`);
  lines.push(`  recordId    String`);
  lines.push(`  status      String`);
  lines.push(`  startedAt   DateTime        @default(now())`);
  lines.push(`  completedAt DateTime?`);
  lines.push(`  error       String?`);
  lines.push(`  nodes       NodeExecution[]`);
  lines.push(`}\n`);

  lines.push(`model NodeExecution {`);
  lines.push(`  id            String      @id @default(uuid())`);
  lines.push(`  workflowRunId String`);
  lines.push(`  workflowRun   WorkflowRun @relation(fields: [workflowRunId], references: [id])`);
  lines.push(`  nodeId        String`);
  lines.push(`  executionMode String`);
  lines.push(`  status        String`);
  lines.push(`  input         Json?`);
  lines.push(`  output        Json?`);
  lines.push(`  startedAt     DateTime    @default(now())`);
  lines.push(`  completedAt   DateTime?`);
  lines.push(`  error         String?`);
  lines.push(`}\n`);

  return lines.join('\n');
}

export function computeIrHash(ir: IntermediateRepresentation): string {
  const str = JSON.stringify({
    domain: ir.domain,
    entities: ir.entities,
    relationships: ir.relationships,
    roles: ir.roles,
    workflows: ir.workflows
  });
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    const char = str.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash |= 0;
  }
  return 'ir_hash_' + Math.abs(hash).toString(16);
}
